### PR TITLE
Update for emoji V11, with caveats:

### PR DESCRIPTION
**Pull request by xaviershay**
* This requires an unreleased fork of emoji-data (https://github.com/iamcal/emoji-data/pull/152)
* Man/woman super hero/villain are missing, because they don't have category data (for some reason)

I don't expect this to be merged as is, but providing here in case useful to others in the mean time.

```
# Before
> cat data/all.json| jq -r ".emojis | keys | .[]" | wc -l 
    1563
# After
> cat data/all.json| jq -r ".emojis | keys | .[]" | wc -l
    1634
```

Name diff before/after:

``` diff
7a8
> abacus
64a66
> badger
65a68
> bagel
78a82
> basket
127a132
> bone
143a149
> bricks
148a155
> broom
193a201
> chess_pawn
249a258
> cold_face
251a261
> compass
288a299
> cupcake
319a331
> dna
409a422,423
> female_bald
> female_curly_haired
413a428
> female_red_haired
415a431
> female_white_haired
426a443,444
> fire_extinguisher
> firecracker
692a711
> flying_disc
695a715
> foot
731a752
> goggles
784a806,807
> hiking_boot
> hippopotamus
790a814
> hot_face
811a836
> infinity
824a850
> jigsaw
830a857
> kangaroo
846a874
> lab_coat
847a876
> lacrosse
854a884
> leafy_green
861a892
> leg
874a906,907
> llama
> lobster
878a912
> lotion_bottle
887a922
> luggage
892a928
> magnet
917a954,955
> male_bald
> male_curly_haired
921a960
> male_red_haired
923a963
> male_white_haired
978a1019
> mango
996a1038
> microbe
1010a1053
> moon_cake
1012a1056
> mosquito
1036a1081
> nazar_amulet
1104a1150
> parrot
1107a1154
> partying_face
1111a1159
> peacock
1127a1176
> petri_dish
1135a1185
> pirate_flag
1138a1189
> pleading_face
1169a1221
> raccoon
1188a1241
> receipt
1190a1244
> red_envelope
1210a1265
> roll_of_paper
1224a1280
> safety_pin
1226a1283
> salt
1270a1328
> skateboard
1291a1350
> smiling_face_with_3_hearts
1304a1364
> soap
1307a1368
> softball
1327a1389
> sponge
1358a1421
> swan
1376a1440
> teddy_bear
1380a1445
> test_tube
1385a1451
> thread
1398a1465,1466
> toolbox
> tooth
1544a1613
> womans_flat_shoe
1546a1616
> woozy_face
1552a1623
> yarn
```

### CODE REVIEW

**Comment by xaviershay** [comment]
(I know this PR should be against `emoji-mart`, just put it here for now coz this is the lib that I use)

**Comment by johnsenpeder** [comment]
@xaviershay yeah looks like they still have it, I can't remember the reason why I upgraded `emoji-datasource` back when I did, but as `emoji-mart` is already behind I'll consider getting this merged in the near future. I'm not sure when `emoji-mart` will follow as it looks like they want to try and keep `emojione` support

**Comment by xaviershay** [comment]
Pushed a commit adding in the missing 4 emoji.

**Comment by pederjohnsen** [comment]
Closing, released new version today which should add support for Emoji 12.1

**Pull request closed without merging**
